<?php
// $Id: mm_schedule.module 4926 2011-01-21 19:18:36Z vquinn $

/**
 * @file
 * Schedule/Calendar functions for Monster Menus
 */

define('MM_SCHEDULE_USER_CALENDAR_DEFAULT_NAME', '.Calendar');
define('MM_SCHEDULE_USER_CALENDAR_ALIAS', 'mycalendar');
define('MM_SCHEDULE_INSTRUCTION_SLASH', 'zzzz');

/**
 * Implementation of hook_theme().
 */
function mm_schedule_theme() {
  return array(
    'mm_schedule_date_combo_all_day' => array(
        'file' => 'mm_schedule_theme.inc',
        'arguments' => array('element' => NULL)),
    'calendar_year__mm_calendar' => array(
        'file' => 'mm_schedule_theme.inc',
        'arguments' => array('view' => NULL, 'options' => NULL)),
    'calendar_month__mm_calendar' => array(
        'file' => 'mm_schedule_theme.inc',
        'arguments' => array('view' => NULL, 'options' => NULL)),
    'calendar_week__mm_calendar' => array(
        'file' => 'mm_schedule_theme.inc',
        'arguments' => array('view' => NULL, 'options' => NULL)),
    'calendar_day__mm_calendar' => array(
        'file' => 'mm_schedule_theme.inc',
        'arguments' => array('view' => NULL, 'options' => NULL)),
    'calendar_view_ical__mm_calendar' => array(
        'file' => 'mm_schedule_theme.inc',
        'arguments' => array('view' => NULL, 'options' => NULL)),
    'mm_schedule_list' => array(
        'file' => 'mm_schedule_theme.inc',
        'arguments' => array('view' => NULL)),
    'mm_schedule' => array(
        'file' => 'mm_schedule_theme.inc',
        'arguments' => array('hours' => NULL, 'days' => NULL, 'events' => NULL, 'options' => NULL)),
  );
}

/**
 * Implementation of hook_menu().
 */
function mm_schedule_menu() {
  $items = array();
  $items['mm_schedule/add2mycalendar/mm/%mm_mmtid'] = array(
    'title' => 'Add All to My Calendar',
    'page callback' => '_mm_schedule_add_to_my_calendar',
    'page arguments' => array(2, 3),
    'access callback' => '_mm_schedule_add_all_to_my_calendar_access',
    'access arguments' => array(3),
  );
  $items['mm_schedule/add2mycalendar/node/%node'] = array(
    'title' => 'Add to My Calendar',
    'page callback' => '_mm_schedule_add_to_my_calendar',
    'page arguments' => array(2, 3),
    'access callback' => '_mm_schedule_add_node_to_my_calendar_access',
    'access arguments' => array(3),
  );
  $items['mm_schedule/del_event/%node/%node'] = array(
    'title' => 'Remove event from calendar',
    'page callback' => '_mm_schedule_remove_event_from_calendar',
    'page arguments' => array(2, 3),
    'access callback' => '_mm_schedule_remove_event_from_calendar_access',
    'access arguments' => array(2, 3),
  );
  $items['mm_schedule/view_event/%/%'] = array(
    'page callback' => '_mm_schedule_view_course',
    'page arguments' => array(2, 3),
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Implementation of hook_elements().
 */
function mm_schedule_elements() {
  $type = array();
  $date_elems = _date_elements();
  if (isset($date_elems['date_combo'])) {
    $type['mm_schedule_date_combo_all_day'] = $date_elems['date_combo'];
    $type['mm_schedule_date_combo_all_day']['#process'][] = '_mm_schedule_date_combo_all_day_process';
  }
  return $type;
}

/**
 * Implementation of hook_node_info().
 */
function mm_schedule_node_info() {
  return array(
    'mm_calendar' => array(
      'name' => t('Event calendar'),
      'module' => 'mm_schedule_mm_calendar',
      'description' => t('Calendars display events in a date-based grid'),
    ),
  );
}

/**
 * Implementation of hook_mm_item_name().
 */
function mm_schedule_mm_item_name() {
  return array(
    MM_SCHEDULE_USER_CALENDAR_DEFAULT_NAME => t('[Calendar default]'),
  );
}

/**
 * Implement hook_mm_hidden_user_names().
 */
function mm_schedule_mm_hidden_user_names() {
  return array(MM_SCHEDULE_USER_CALENDAR_DEFAULT_NAME);
}

/**
 * Implementation of hook_mm_node_info().
 */
function mm_schedule_mm_node_info() {
  return array(
    // mm_event is a CCK content type, but we need to set flags to prevent
    // MM from rendering and allowing users to create or reorder this node type.
    'mm_event' => array(
      MM_NODE_INFO_NO_RENDER => TRUE,
      MM_NODE_INFO_ADD_HIDDEN => TRUE,
      MM_NODE_INFO_NO_REORDER => TRUE,
    )
  );
}

/**
 * Implementation of hook_mm_url_rewrite_outbound().
 */
function mm_schedule_mm_url_rewrite_outbound($mmtid, &$path, &$options, $original_path) {
  $args = explode('/', $path);
  if ($args[0] == '.mm_calendar') {
    $query = array();
    if (!empty($options['query'])) {
      $query = split('&', $options['query']);
      foreach ($query as $key => $value)
        if (strpos($value, 'mm_calendar=') === 0) {
          unset($query[$key]);
        }
    }

    array_shift($args);                           // skip .mm_calendar
    if (preg_match('{^\d+(\+|$)}', $args[0])) array_shift($args); // skip any node number

    foreach ($args as $key => $value)
      if (preg_match('{^[-0-9W]+$}', $value)) {
        array_splice($args, $key + 1);
        break;
      }

    // Preserve old mode (grid or list)
    if (preg_match('{^([a-z]+)(/|$)}', $_GET['mm_calendar'], $matches)) {
      array_unshift($args, $matches[1]);
    }

    $query[] = 'mm_calendar=' . urlencode(join('/', $args));
    $options['query'] = join('&', $query);
    $path = "mm/$mmtid";
  }
  else if (empty($options['query']) && !empty($_GET['mm_calendar'])) {
    $options['query'] = drupal_query_string_encode(array('destination' => "mm/$mmtid?mm_calendar=" . $_GET['mm_calendar']));
  }
}

function mm_schedule_my_calendar_access() {
  global $user;
  return $user->uid > 0 && user_access('has personal calendar');
}

/**
 * Implementation of hook_perm().
 */
function mm_schedule_perm() {
  return array('create mm_calendars', 'edit own mm_calendars', 'has personal calendar');
}

/**
 * Implementation of hook_access().
 */
function mm_schedule_mm_calendar_access($op, $node, $account) {
  if ($op == 'create') {
    // Only users with permission to do so may create this node type.
    return user_access('create mm_calendars', $account);
  }

  // Users who create a node may edit or delete it later, assuming they have the
  // necessary permissions.
  if ($op == 'update' || $op == 'delete') {
    if (user_access('edit own mm_calendars', $account) && ($account->uid == $node->uid)) {
      return TRUE;
    }
  }
}

/**
 * Implementation of hook_form().
 */
function mm_schedule_mm_calendar_form(&$node) {
  drupal_set_title($node->nid ? t('Edit a calendar') : t('Create a calendar'));

  $type = node_get_types('type', $node);
  $form['title'] = array('#type' => 'textfield', '#title' => check_plain($type->title_label), '#required' => TRUE, '#default_value' => $node->title, '#weight' => -5);
  $form['body_filter']['body'] = array('#type' => 'textarea', '#title' => check_plain($type->body_label), '#default_value' => $node->body, '#rows' => 20);
  $form['body_filter']['filter'] = filter_form($node->format);

  return $form;
}

/**
 * Implementation of hook_view().
 */
function mm_schedule_mm_calendar_view($node, $teaser = FALSE, $page = FALSE) {
  global $user;

  if ($teaser) {
    $node = node_prepare($node, $teaser);
    $node->readmore = TRUE;
    return $node;
  }

  mm_parse_args($term_ids, $oarg_list, $this_tid);
  if (!isset($this_tid)) {
    if (isset($node->mm_calendar_mmtid)) $this_tid = $node->mm_calendar_mmtid;
    else {
      $with_node = mm_content_get_by_nid($node->nid);
      if (!count($with_node)) {
        return node_prepare($node, $teaser);
      }
      $this_tid = $with_node[0];
    }
  }

  $view = views_get_view('mm_calendar');
  if (!$view) return $node;

  // Set the granularity (month, day, week, etc.) of both arguments to the
  // same default value.
  if (isset($node->field_default_display))
    $granularity = $view->display['default']->display_options['arguments']['date_argument']['granularity'] = $view->display['default']->display_options['arguments']['date_argument_1']['granularity'] = $node->field_default_display[0]['value'];

  $args = array();
  $displays = array('ical' => 'calendar_ical_1', 'list' => 'default', 'grid' => 'calendar_1');
  $display_mode = $node->field_default_view[0]['value'];
  if (empty($display_mode)) $display_mode = 'grid';
  $display = $displays[$display_mode];

  if (!empty($_GET['mm_calendar'])) {
    $args = split('/', $_GET['mm_calendar']);
    // Is there a specific view mode in the URL?
    if (isset($displays[$args[0]])) {
      $display = $displays[$args[0]];
      $display_mode = $args[0];
      array_shift($args);
    }

    if (empty($args[0])) {
      $args = array();
    }
    else {
      // Make both arguments the same
      $args[1] = $args[0];
    }
  }

  $view->mm_first_month = $node->field_first_month[0]['value'];
  if (!$args && $granularity === 'year' && date('n') < $view->mm_first_month) {
    // If using default args and the current month is before the start of the
    // calendar year, show last year
    $args[0] = $args[1] = date('Y') - 1;
  }

  $nids = array($node->nid);
  if ($node->mycalendar) {
    // Add calendar nodes that are "pushed" to this user
    $result = db_query(
      'SELECT DISTINCT n.nid FROM {mm_group} g ' .
      'LEFT JOIN {mm_virtual_group} v ON v.vgid = g.vgid ' .
      'INNER JOIN {content_field_mm_groups} c ON c.field_mm_groups_value = g.gid ' .
      'INNER JOIN {node} n ON n.vid = c.vid ' .
      'WHERE v.uid = %d OR g.vgid = 0 AND g.uid = %d', $user->uid, $user->uid);
    while ($row = db_fetch_object($result)) {
      if ($row->nid != $node->nid) $nids[] = $row->nid;
    }
  }

  $view->mm_came_from = '';
  if ($display_mode != 'ical') {
    $view->mm_came_from = "$this_tid:$display_mode:$args[0]:$node->nid";
  }

  array_unshift($args, join('+', $nids));

  $view->mm_node =& $node;    // used in monster_menus_preprocess_calendar_main()
  $view->mmtid = $this_tid;
  $view->mm_display_mode = $display_mode;
  if (isset($node->mm_calendar_mmtid)) $view->mm_calendar_mmtid = $node->mm_calendar_mmtid;

  $output = $view->execute_display($display, $args);
  if ($display_mode == 'ical') exit();

  $node->content['mm_calendar'] = array(
    '#value' => $node->body . $output,
    '#weight' => 1,
  );
  return $node;
}

/**
 * Implementation of hook_views_pre_execute().
 */
function mm_schedule_views_pre_execute($view) {
  // Move the starting and ending dates when the node's creator has said the
  // year starts in a month other than January
  if ($view->name == 'mm_calendar' && isset($view->mm_node) && isset($view->argument['date_argument']) && $view->argument['date_argument']->granularity == 'year' && $view->mm_first_month > 1) {
    if (!isset($view->mm_fixed_month)) {
      $offset = '+' . ($view->mm_first_month - 1) . ' month';
      date_modify($view->argument['date_argument']->min_date, $offset);
      date_modify($view->argument['date_argument']->max_date, $offset);
      $view->mm_fixed_month = TRUE;
    }

    // Unfortunately, the query is first built before $view->date_info is fully populated
    if (isset($view->date_info->min_date)) {
      $view->date_info->min_date = $view->argument['date_argument']->min_date;
      $view->date_info->max_date = $view->argument['date_argument']->max_date;
    }

    $view->date_info->min_date_date = date_format($view->argument['date_argument']->min_date, DATE_FORMAT_DATE);
    $view->date_info->max_date_date = date_format($view->argument['date_argument']->max_date, DATE_FORMAT_DATE);

    $from = array(
      '{(DATE_FORMAT\(ADDTIME\(.*?\),\s*\')%Y(\'\)\s*>=\s*)\'\d\d\d\d\'}',
      '{(DATE_FORMAT\(ADDTIME\(.*?\),\s*\')%Y(\'\)\s*<=\s*)\'\d\d\d\d\'}');
    $to = array(
      '\1%Y-%m\2\'' . substr($view->date_info->min_date_date, 0, 7) . "'",
      '\1%Y-%m\2\'' . substr($view->date_info->max_date_date, 0, 7) . "'");
    $view->build_info['query'] = preg_replace($from, $to, $view->build_info['query']);
    $view->build_info['count_query'] = preg_replace($from, $to, $view->build_info['count_query']);
  }
}

/**
 * Implementation of hook_mm_copy_tree_node_alter().
 */
function mm_schedule_mm_copy_tree_node_alter(&$node, $old_catlist) {
  if ($node->type == 'mm_calendar') {
    // When copying a calendar node, update the list of subscribed pages to
    // point to the new node's location
    $old_catlist = array_keys($old_catlist);
    foreach ($node->field_mm_pages as $pos => $mm_page)
      if (array_search($mm_page['value'], $old_catlist) !== FALSE) {
        $new_cat = array_keys($node->mm_catlist);
        $node->field_mm_pages[$pos]['value'] = $new_cat[0];
      }
  }
}

function mm_schedule_preprocess_calendar_main(&$vars) {
  $view = $vars['view'];
  if (isset($view->mm_node) && $view->mm_node->type == 'mm_calendar') {
    $mmtid = $view->mmtid;
    $calendar_mmtid = isset($view->mm_calendar_mmtid) ? $view->mm_calendar_mmtid : $mmtid;

    if (!$view->mm_node->field_allow_mode_change[0]['value']) {
      $vars['calendar_links'] = array();
    }
    else {
      // Grid/List
      $params = array(
        'grid' => array('list', t('List'), t('View this calendar in a simple list')),
        'list' => array('grid', t('Grid'), t('View this calendar in a grid')),
      );
      $new_mode = $params[$view->mm_display_mode];
      $get = $_GET;
      $get['mm_calendar'] = join('/', array($new_mode[0], preg_replace('{^[a-z]+(/|$)}', '', $get['mm_calendar'])));
      $vars['calendar_links'][] = array(
        'title' => $new_mode[1],
        'href' => "mm/$mmtid",
        'query' => drupal_query_string_encode($get, array('q')),
        'attributes' => array(
          'title' => $new_mode[2],
          'class' => 'schedule-link-space-before',
          'rel' => 'nofollow',
        ),
      );
    }

    // Export
    if ($view->mm_node->field_show_export[0]['value']) {
      $get = $_GET;
      $get['mm_calendar'] = join('/', array('ical', preg_replace('{^[a-z]+(/|$)}', '', $get['mm_calendar'])));
      $vars['calendar_links'][] = array(
        'title' => t('Export'),
        'href' => "mm/$mmtid",
        'query' => drupal_query_string_encode($get, array('q')),
        'attributes' => array(
          'title' => t('Export this calendar view in iCal format'),
          'class' => 'schedule-link-space-before',
          'rel' => 'nofollow',
        ),
      );
    }

    // Add event
    if (_mm_schedule_can_add_event($calendar_mmtid)) {
      $query = array('destination' => "mm/$mmtid%3F" . drupal_query_string_encode($_GET, array('q')));
      if (!empty($_GET['mm_calendar'])) $query['mm_event_start'] = date_format($view->date_info->min_date, DATE_FORMAT_DATETIME);
      $vars['calendar_links'][] = array(
        'title' => t('Add event'),
        'href' => "mm/$calendar_mmtid/contents/add/mm_event",
        'query' => $query,
        'attributes' => array(
          'title' => t('Add a new event to this calendar'),
          'class' => 'schedule-link-space-before',
        ),
      );
    }

    unset($view->feed_icon);
  }
}

/**
 * Implementation of hook_mm_links_order().
 */
function mm_schedule_mm_links_order(&$order) {
  $order = array_merge($order, array(
    '{^Day}i',
    '{^Week}i',
    '{^Month}i',
    '{^Year}i',
    '{^List}i',
    '{^Grid}i',
    '{^Export}i',
    '{^Add event}i',
    '{^Add to My Calendar}i',
    '{^Add All to My Calendar}i',
    '{^Return to Calendar}i',
  ));
}

/**
 * Implementation of hook_link_alter().
 */
function mm_schedule_link_alter(&$links, &$node) {
  if ($node->type == 'mm_calendar')
    foreach ($links as $num => $link)
      if (empty($link['query'])) {
        $mm = mm_parse_args($term_ids, $oarg_list, $this_tid, $link['href']);
        if ($oarg_list[0] == 'node') {
          $query = drupal_query_string_encode($_GET, array('q'));
          if (!empty($query)) $query = '%3F' . $query;
          $links[$num]['query'] = array('destination' => "mm/$this_tid$query");
        }
      }
}

/**
 * Implementation of hook_link().
 */
function mm_schedule_link($type, $node, $teaser = FALSE) {
  $links = array();
  if (!$teaser && isset($node) && node_access('view', $node)) {
    if ($node->type == 'mm_event') {
      if (isset($_REQUEST['destination'])) {
        $query = drupal_query_string_encode(array('destination' => $_REQUEST['destination']));
        $dest = parse_url(urldecode($_REQUEST['destination']));
        $links[] = array('title' => t('Return to Calendar'), 'href' => $dest['path'], 'query' => $dest['query']);
      }
      else {
        $mm = mm_parse_args($term_ids, $oarg_list, $this_tid);
        $query = $this_tid ? array('destination' => "mm/$this_tid") : '';
      }

      if (user_access('has personal calendar') && !mm_content_node_is_recycled($node)) {
        list($cat_exists, $node_exists) = mm_schedule_my_calendar_exists();
        if (empty($node_exists) || mm_schedule_event_is_on_calendar($node_exists, 'node', $node) === FALSE) {
          $links[] = array(
            'title' => t('Add to My Calendar'),
            'href' => 'mm_schedule/add2mycalendar/node/' . $node->nid,
            'query' => $query,
            'attributes' => array(
              'title' => t('Add all occurrences of this event to your personal calendar'),
            ),
          );
        }
      }
    }
    else if ($node->type == 'mm_calendar') {
      if (user_access('has personal calendar') && !isset($node->mm_calendar_mmtid)) {
        $mm = mm_parse_args($term_ids, $oarg_list, $this_tid);
        $query = $this_tid ? array('destination' => "mm/$this_tid") : '';

        list($cat_exists, $node_exists) = mm_schedule_my_calendar_exists();
        if (empty($node_exists) || mm_schedule_event_is_on_calendar($node_exists, 'mm', $this_tid) === FALSE) {
          $links[] = array(
            'title' => t('Add All to My Calendar'),
            'href' => 'mm_schedule/add2mycalendar/mm/' . $this_tid,
            'query' => $query,
            'attributes' => array(
              'title' => t('Add all events on this calendar to your personal calendar'),
            ),
          );
        }
      }
    }
  }
  return $links;
}

/**
 * Implementation of hook_views_plugins
 */
function mm_schedule_views_plugins() {
  if (function_exists('calendar_ical_views_plugins')) {
    module_load_include('inc', 'mm_schedule', 'mm_schedule.views');
    return _mm_schedule_views_plugins();
  }
}

/**
 * Implementation of hook_form_alter().
 */
function mm_schedule_form_alter(&$form, $form_state, $form_id) {
  if (isset($form['type']) && isset($form['#node']) && $form['type']['#value'] . '_node_form' == $form_id) {
    if ($form_id == 'mm_event_node_form') {
      $form['scheduling']['#access'] = FALSE;
      $form['mm_appearance']['sticky']['#access'] = FALSE;
      $form['comment_settings']['#access'] = FALSE;
      $form['mm_categories']['#access'] = FALSE;
      if (isset($form['field_start_datetime'])) {
        $form['field_start_datetime']['#type'] = 'mm_schedule_date_combo_all_day';
        $form['field_start_datetime']['#after_build'][] = '_mm_schedule_date_combo_all_day_after_build';
        $form['field_start_datetime']['rrule']['#after_build'][] = '_mm_schedule_rrule_after_build';

        if (!isset($form['#node']->nid)) {
          $tz = date_default_timezone();
          if (isset($_GET['mm_event_start']))
            $start = date_create($_GET['mm_event_start'], $tz);

          if (empty($start)) {
            $start = date_create($form['field_start_datetime']['#default_value']['value'], $tz);
            date_modify($start, '+1 hour');
            date_modify($start, '-' . date_format($start, 'i') . ' minutes');
          }

          if (isset($_GET['mm_event_end']))
            $end = date_create($_GET['mm_event_end'], $tz);

          if (empty($end)) {
            $end = drupal_clone($start);
            date_modify($end, '+1 hour');
          }

          $form['field_start_datetime']['#default_value']['value']  = date_format($start, 'Y-m-d H:i:00');
          $form['field_start_datetime']['#default_value']['value2'] = date_format($end, 'Y-m-d H:i:00');
        }
      }
    }
    else if ($form_id == 'mm_calendar_node_form') {
      // Put display options into a table
      $old_weight = $form['group_appearance']['field_default_display']['#weight'];
      $form['group_appearance']['field_default_display']['#weight'] = 2001;
      $form['group_appearance']['field_default_display']['#required'] = FALSE;
      $form['group_appearance']['field_default_view']['#weight'] = 2002;
      $form['group_appearance']['field_default_view']['#required'] = FALSE;
      $form['group_appearance']['defaults'] = array(
        '#weight' => $old_weight,
        '#theme' => 'form_panel_table',
        'field_default_display' => $form['group_appearance']['field_default_display'],
        'field_default_view' => $form['group_appearance']['field_default_view']
      );
      unset($form['group_appearance']['field_default_display']);
      unset($form['group_appearance']['field_default_view']);

      // Move Week/Day Grid Settings
      $form['group_week_day']['#weight'] = 98;
      $form['group_week_day']['#theme'] = 'form_panel_table';
      $form['group_week_day']['field_wd_start']['#weight'] = 2001;
      $form['group_week_day']['field_wd_start']['#required'] = FALSE;
      $form['group_week_day']['field_wd_end']['#weight'] = 2002;
      $form['group_week_day']['field_wd_end']['#required'] = FALSE;
      $form['group_week_day']['field_wd_increment']['#weight'] = 2003;
      $form['group_week_day']['field_wd_increment']['#required'] = FALSE;
      $form['group_appearance']['group_week_day'] = $form['group_week_day'];
      unset($form['group_week_day']);

      // Move Year Settings
      $form['group_year']['#weight'] = 99;
      $form['group_year']['field_first_month']['#required'] = FALSE;
      $form['group_appearance']['group_year'] = $form['group_year'];
      unset($form['group_year']);

      // Only admins can push to My Calendar
      $form['group_push']['#access'] = user_access('administer all menus');
    }
  }
}

/**
 * Implementation of hook_mm_delete().
 */
function mm_schedule_mm_delete($mmtids, $nids) {
  if ($mmtids) {
    db_query('DELETE FROM {content_field_mm_pages} WHERE field_mm_pages_value IN(' . db_placeholders($mmtids) . ')', $mmtids);
  }
}

/**
 * Implementation of hook_nodeapi().
 */
function mm_schedule_nodeapi(&$node, $op, $a3, $a4) {
  switch ($op) {
    case 'presave':
      if ($node->type != 'mm_calendar') break;

      // For each page the user has chosen, load any mm_calendar nodes and add
      // the pages and nodes it refers to, recursively
      $nodes = $pages = array();
      if (is_array($node->field_mm_pages))
        foreach ($node->field_mm_pages as $page)
          if (!empty($page['value'])) $pages[$page['value']] = TRUE;

      if (is_array($node->field_mm_events))
        foreach ($node->field_mm_events as $mm_event)
          if (!empty($mm_event['nid'])) $nodes[$mm_event['nid']] = TRUE;

      if ($pages) {
        $test_pages = array_keys($pages);
        $skip_nids = array($node->nid);
        do {
          $result = db_query("SELECT n.nid FROM {mm_node2tree} n2 INNER JOIN {node} n ON n.nid = n2.nid WHERE n.type = 'mm_calendar' AND mmtid IN(" . db_placeholders($test_pages) . ') AND n.nid NOT IN(' . db_placeholders($skip_nids) . ')', array_merge($test_pages, $skip_nids));
          $test_pages = array();
          while ($other = db_fetch_object($result)) {
            $skip_nids[] = $other->nid;
            if (mm_content_user_can_node($other, 'r') && ($other_node = node_load($other->nid))) {
              if (is_array($other_node->field_mm_events))
                foreach ($other_node->field_mm_events as $mm_event)
                  $nodes[$mm_event['nid']] = TRUE;

              if (is_array($other_node->field_mm_pages))
                foreach ($other_node->field_mm_pages as $page)
                  if (!isset($pages[$page['value']])) {
                    $pages[$page['value']] = TRUE;
                    $test_pages[] = $page['value'];
                  }
            }
          }
        }
        while ($test_pages);
      }

      $node->field_mm_pages = $node->field_mm_events = array();
      foreach (array_keys($pages) as $page)
        $node->field_mm_pages[]['value'] = $page;

      foreach (array_keys($nodes) as $nid)
        $node->field_mm_events[]['nid'] = $nid;
  }
}

function mm_schedule_my_calendar() {
  global $user, $_mm_mmtid_of_node;

  if ($user->uid == 0) return;

  list($mmtid, $node) = mm_schedule_create_my_calendar();

  if (empty($mmtid)) return;

  if (!mm_content_user_can_node($node, 'r')) return;

  if (mm_content_user_can_node($node, 'w')) $user->mycalendar_nid = $node->nid;

  $node->mycalendar = TRUE;

  $node->mm_calendar_mmtid = $mmtid;
  $_mm_mmtid_of_node[$node->nid] = $mmtid;

  return mm_node_show($node, 0);
}

function mm_schedule_my_calendar_exists($user_obj = NULL) {
  global $user;

  if (!$user_obj) $user_obj = $user;
  $cat_exists = mm_content_get(array('alias' => MM_SCHEDULE_USER_CALENDAR_ALIAS,
    'parent' => $user_obj->user_mmtid));
  if (count($cat_exists)) {
    $exists = $cat_exists[0]->mmtid;
    $nid = _mm_schedule_calendar_on_page($exists);
    if (!empty($nid)) {
      return array($exists, node_load($nid));
    }
    return array($exists, NULL);
  }
}

function mm_schedule_create_my_calendar() {
  global $user;

  if (empty($user->user_mmtid) || $user->uid <= 0 || !user_access('create mm_calendars')) return;

  $default_cat = mm_schedule_create_default_calendar();
  if (!is_numeric($default_cat)) return;

  // If page exists, but not node, copy just the node.
  // Otherwise, copy everything.
  $copy_page = TRUE;
  $dest = $user->user_mmtid;
  list($cat_exists, $node) = mm_schedule_my_calendar_exists();
  if (!empty($cat_exists)) {
    $copy_page = FALSE;
    $dest = $cat_exists;
    if (!empty($node)) return array($dest, $node);
  }

  $copy_params = array(
    MM_COPY_ALIAS =>    MM_SCHEDULE_USER_CALENDAR_ALIAS,
    MM_COPY_CONTENTS => TRUE,
    MM_COPY_NAME =>     t('My Calendar'),
    MM_COPY_OWNER =>    $user->uid,
    MM_COPY_RECUR =>    FALSE,
    MM_COPY_TREE =>     $copy_page,
  );
  $new_tid = mm_content_copy($default_cat, $dest, $copy_params);

  if (!is_numeric($new_tid)) {
    watchdog('mm_schedule', 'Error copying default user calendar: %err', array('%err' => $new_tid), WATCHDOG_ERROR);
    return;
  }

  $nid = _mm_schedule_calendar_on_page($new_tid);
  if (!empty($nid) && ($node = node_load($nid))) {
    $node->revision = FALSE;
    $node->field_mm_pages = array(array('value' => $new_tid));
    $node->uid = $user->uid;
    $node->name = $user->name;
    $node->owner = array($user->uid => $user->name);
    node_save($node);
    return array($new_tid, $node);
  }
}

function _mm_schedule_get_node_link($node, $default = NULL) {
  if (isset($node->url)) {
    return $node->url;
  }
  elseif (empty($node->remote) && is_numeric($node->nid)) {
    return "node/$node->nid";
  }
  elseif (!empty($default)) {
    return $default;
  }
}

/* Overrides theme_jcalendar_view() in modules/calendar/jcalendar/jcalendar.module */
function phptemplate_jcalendar_view($node) {
  global $user;

  $output = node_view($node, TRUE);
  $links = array();
  if (is_numeric($node->nid)) {
    $prefix = '';
    $options = array();
    $args = explode(':', $_GET['q']);
    if (!empty($args[5])) {
      $mmtid = $args[5];
      $mm_calendar = $args[6] . '/' . $args[7];
      $options = array('query' => array('destination' => "mm/$mmtid%3F" . drupal_query_string_encode(array('mm_calendar' => $mm_calendar))));
      $prefix = "mm/$mmtid/";
    }

    $links[] = l(t('Details'), $prefix . _mm_schedule_get_node_link($node), $options);

    if (node_access('update', $node))
      $links[] = l(t('Edit'), "{$prefix}node/$node->nid/edit", $options);

    if (_mm_menu_access_node_delete($node)) {
      $links[] = l(mm_content_node_is_recycled($node) ? t('Delete permanently') : t('Delete'),
        "{$prefix}node/$node->nid/delete", $options);
    }

    $is_signed_up = FALSE;
    if (!empty($node->signup_status) && module_exists('signup')) {
      $is_signed_up = db_result(db_query("SELECT COUNT(*) FROM {signup_log} WHERE nid = %d AND uid = %d", $node->nid, $user->uid));
      $text = $is_signed_up ? t('Cancel sign up') : t('Sign up');
      $links[] = l($text, $prefix . _mm_schedule_get_node_link($node), $options);
    }

    if (!$is_signed_up && ($cal_nid = intval($args[8])) != 0 && ($cal_node = node_load($cal_nid)) && _mm_schedule_remove_event_from_calendar_access($cal_node, $node)) {
      $options2 = $options;
      $options2['attributes']['id'] = 'del-from-cal';
      $options2['attributes']['title'] = t('Remove this event from the current calendar');
      $url = 'mm_schedule/del_event/' . $cal_node->nid . '/' . $node->nid;
      $links[] = l(t('Remove from calendar'), $url, $options2);
      $output .= '<script type="text/javascript">' . _mm_schedule_subrequest_js('del-from-cal', "$url/js", "div[id^=calendar:$node->nid:]") . '</script>';
    }

    if (mm_schedule_my_calendar_access() && !mm_content_node_is_recycled($node)) {
      list($cat_exists, $node_exists) = mm_schedule_my_calendar_exists();
      if (empty($node_exists) || mm_schedule_event_is_on_calendar($node_exists, 'node', $node) === FALSE) {
        $options2 = $options;
        $options2['attributes']['id'] = 'add-to-my-cal';
        $options2['attributes']['title'] = t('Add all occurrences of this event to your personal calendar');
        $url = 'mm_schedule/add2mycalendar/node/' . $node->nid;
        $links[] = l(t('Add to My Calendar'), $url, $options2);
        $output .= '<script type="text/javascript">' . _mm_schedule_subrequest_js('add-to-my-cal', "$url/js") . '</script>';
      }
    }
  }
  else {
    $links[] = l(t('Details'), calendar_get_node_link($node));
  }
  $output .= '<div id="nodelink">'. join(' ', $links) .'</div>';
  return $output;
}

function mm_schedule_create_default_calendar() {
  $users_tid = mm_content_users_mmtid();
  $default_cat = mm_content_get(array('name' => MM_SCHEDULE_USER_CALENDAR_DEFAULT_NAME, 'parent' => $users_tid));
  if (count($default_cat)) $default_cat = $default_cat[0]->mmtid;
  else {
    $default_cat = mm_content_insert_or_update(TRUE, $users_tid, array(
      'name' => MM_SCHEDULE_USER_CALENDAR_DEFAULT_NAME,
      'default_mode' => '',
      'uid' => 1,
      'flags' => array('limit_alias' => '', 'limit_move' => '', 'limit_delete' => '', 'limit_hidden' => '', 'limit_location' => '', 'limit_name' => '', 'limit_write' => ''),
      'node_info' => FALSE,
    ));
    if (!$default_cat) {
      watchdog('mm_schedule', 'Error creating default user calendar', array(), WATCHDOG_ERROR);
      return t('Error creating default user calendar');
    }
  }

  $nodes = mm_content_get_nids_by_mmtid($default_cat, 1);
  if (!count($nodes)) {
    $admin = user_load(1);
    $form_state = array();
    $node = array('type' => 'mm_calendar');
    $form_state['values'] = array(
      'uid' => $admin->uid,
      'name' => $admin->name,
      'title' => t('My Calendar'),
      'body' => '',
      'status' => 1,
      'comment' => 0,
      'mm_catlist' => array($default_cat => ''),
      'owner' => array($admin->uid => $admin->name),
      'groups_w' => array(),
      'users_w' => array(),
      'show_node_info' => 0,
      '_via_drupal_execute' => TRUE,
      'op' => t('Save'),
      'field_wd_increment' => '',
    );
    $form_state['node'] = $node;
    module_load_include('inc', 'node', 'node.pages');
    drupal_execute('mm_calendar_node_form', $form_state, (object)$node);
  }

  return $default_cat;
}

function _mm_schedule_calendar_on_page($mmtid) {
  return mm_query_result("SELECT n2.nid FROM {mm_node2tree} n2 INNER JOIN {node} n ON n.nid = n2.nid WHERE n.type = 'mm_calendar' AND n2.mmtid = %d ORDER BY n.created LIMIT %d", $mmtid, 1);
}

function _mm_schedule_add_node_to_my_calendar_access($node) {
  return mm_schedule_my_calendar_access() && node_access('view', $node);
}

function _mm_schedule_add_all_to_my_calendar_access($mmtid) {
  return mm_schedule_my_calendar_access() && mm_content_user_can($mmtid, 'r');
}

function _mm_schedule_remove_event_from_calendar_access($cal_node, $node) {
  return mm_content_user_can_node($cal_node, 'w') && mm_schedule_event_is_on_calendar($cal_node, 'node', $node->nid) === 'node';
}

function mm_schedule_event_is_on_calendar($cal_node, $type, $node_or_nid_or_mmtid) {
  if ($type == 'mm') {
    if (is_array($cal_node->field_mm_pages))
      foreach ($cal_node->field_mm_pages as $page)
        if ($page['value'] == $node_or_nid_or_mmtid) return 'mm';
  }
  else {
    $nid = is_object($node_or_nid_or_mmtid) ? $node_or_nid_or_mmtid->nid : $node_or_nid_or_mmtid;
    if (is_array($cal_node->field_mm_events))
      foreach ($cal_node->field_mm_events as $event)
        if ($event['nid'] == $nid) return 'node';

    if (is_array($cal_node->field_mm_pages)) {
      $test_pages = array();
      foreach ($cal_node->field_mm_pages as $page)
        $test_pages[] = $page['value'];

      $args = $test_pages;
      $args[] = $nid;
      if (mm_query_result('SELECT COUNT(*) FROM {mm_node2tree} WHERE mmtid IN(' . db_placeholders($test_pages) . ') AND nid = %d', $args)) return 'mm';
    }
  }

  return FALSE;
}

function _mm_schedule_remove_event_from_calendar($cal_node, $node, $js = NULL) {
  if (is_array($cal_node->field_mm_events))
    foreach ($cal_node->field_mm_events as $index => $event)
      if ($event['nid'] == $node->nid) {
        $cal_node->revision = FALSE;
        unset($cal_node->field_mm_events[$index]);
        node_save($cal_node);
        break;
      }

  $return = t('All occurrences of this event have been removed from the calendar.');
  if (empty($js)) {
    if (isset($_REQUEST['destination'])) {
      drupal_set_message($return);
      drupal_goto();
    }
    return $return;
  }

  $GLOBALS['devel_shutdown'] = FALSE;
  drupal_set_header('Content-Type: text/html; charset=utf-8');
  print $return;
  exit();
}

function _mm_schedule_add_to_my_calendar($type, $node_or_mmtid, $js = NULL) {
  list($mmtid, $cal_node) = mm_schedule_create_my_calendar();

  $return = '';
  if (empty($mmtid)) {
    $return = t('A personal calendar could not be created.');
  }
  else if (!mm_content_user_can_node($cal_node, 'w')) {
    $return = t('You do not have permission to modify your personal calendar.');
  }
  else {
    if ($type == 'mm') {    // all events using mmtid
      if (!mm_content_user_can($node_or_mmtid, 'r')) {
        $return = t('You do not have permission to read the source calendar.');
      }
      else if (mm_schedule_event_is_on_calendar($cal_node, $type, $node_or_mmtid) !== FALSE) {
        $return = t('All events from this calendar are already present on your personal calendar.');
      }
      else {
        $cal_node->revision = FALSE;
        $cal_node->field_mm_pages[] = array('value' => $node_or_mmtid);
        node_save($cal_node);
        $return = t('All events from this calendar have been added to your personal calendar.');
      }
    }
    else {                  // single event using node
      if ($node_or_mmtid->type != 'mm_event') {
        $return = t('Incorrect node type');
      }
      else if (mm_schedule_event_is_on_calendar($cal_node, $type, $node_or_mmtid) !== FALSE) {
        $return = t('This event is already present on your personal calendar.');
      }
      else {
        $cal_node->revision = FALSE;
        $cal_node->field_mm_events[] = array('nid' => $node_or_mmtid->nid);
        node_save($cal_node);
        $return = t('This event has been added to your personal calendar.');
      }
    }
  }

  if (empty($js)) {
    if (isset($_REQUEST['destination'])) {
      drupal_set_message($return);
      drupal_goto();
    }
    return $return;
  }

  $GLOBALS['devel_shutdown'] = FALSE;
  drupal_set_header('Content-Type: text/html; charset=utf-8');
  print $return;
  exit();
}

function _mm_schedule_cancel_or_insert_signup($signup, $mode) {
  global $user;

  $user_obj = user_load($signup->uid);
  if ($user_obj && $user_obj->uid) {
    list($mmtid, $cal_node) = mm_schedule_my_calendar_exists($user_obj);

    if ($mode == 'insert' && empty($cal_node)) {
      list($mmtid, $cal_node) = mm_schedule_create_my_calendar();
    }

    if (!empty($mmtid) && !empty($cal_node) && mm_content_user_can_node($cal_node, 'w', $user_obj)) {
      $found = FALSE;
      if (is_array($cal_node->field_mm_events)) {
        foreach ($cal_node->field_mm_events as $index => $subscribed) {
          if ($subscribed['nid'] == $signup->nid) {
            $found = $index;
            break;
          }
        }
      }

      $cal_node->revision = FALSE;
      if ($mode == 'cancel' && $found !== FALSE) {
        unset($cal_node->field_mm_events[$index]);
        node_save($cal_node);
        if ($signup->uid == $user->uid) {
          drupal_set_message(t('This event has been removed from your personal calendar.'));
        }
      }
      else if ($mode == 'insert' && $found === FALSE) {
        $cal_node->field_mm_events[] = array('nid' => $signup->nid);
        node_save($cal_node);
        if ($signup->uid == $user->uid) {
          drupal_set_message(t('This event has been added to your personal calendar.'));
        }
      }
    }
  }
}

function _mm_schedule_date_combo_all_day_process($element, $edit, &$form_state, $form) {
  $is_all_day = FALSE;
  if (is_string($element['#value']['value'])) {
    $granularity = $element['value']['#field']['granularity'];
    $date1 = empty($element['#value']['value']) ? date('Y-m-d') : substr($element['#value']['value'], 0, 10);
    $all_day1 = "$date1 00:00:00";
    $date2 = empty($element['#value']['value2']) ? date('Y-m-d') : substr($element['#value']['value2'], 0, 10);
    $all_day2 = date_limit_value("$date2 23:59:59", $granularity);
    $is_all_day = $element['#value']['value'] == $all_day1 && $element['#value']['value2'] == $all_day2;
    $time_granularity = array_intersect($granularity, array('hour', 'minute', 'second'));
    $time_format = date_popup_format_to_popup_time(date_limit_format($element['value']['#date_format'], $time_granularity));
    $min_time = date($time_format, date_convert($all_day1, DATE_DATETIME, DATE_UNIX, date_default_timezone_name()));
    $max_time = date($time_format, date_convert($all_day2, DATE_DATETIME, DATE_UNIX, date_default_timezone_name()));
  }
  else {
    $min_time = $element['#post'][$element['#field_name']]['all_day_min_time'];
    $max_time = $element['#post'][$element['#field_name']]['all_day_max_time'];
  }

  $element['all_day_min_time'] = array(
    '#type' => 'hidden',
    '#input' => TRUE,
    '#value' => $min_time,
  );
  $element['all_day_max_time'] = array(
    '#type' => 'hidden',
    '#input' => TRUE,
    '#value' => $max_time,
  );
  $element['#theme'] = 'form_panel_table';
  $element['#form_panel_table_attributes'] = array('class' => 'mm-date-combo-all-day');
  $element['#form_panel_number_cols'] = TRUE;
  $element['value']['#weight'] = 2001;
  $element['value2']['#weight'] = 2002;
  $element['is_all_day'] = array(
    '#type' => 'checkbox',
    '#input' => TRUE,
    '#title' => t('All day event'),
    '#default_value' => $is_all_day,
    '#weight' => 2003,
  );
  if (isset($element['rrule'])) $element['rrule']['#weight'] = 3001;

  drupal_add_js(_mm_schedule_date_combo_js($element['#id'], $element['#field_name']), 'inline', 'footer');
  return $element;
}

function _mm_schedule_date_combo_all_day_after_build($element, &$form_state) {
  if (is_array($element['value']['#value']) && is_array($element['value2']['#value']) && $form_state['values'][$element['#name']]['is_all_day']) {
    $element['value']['#value']['time'] = $element['#post'][$element['#name']]['value']['time'] = $form_state['values'][$element['#name']]['all_day_min_time'];
    $element['value2']['#value']['time'] = $element['#post'][$element['#name']]['value2']['time'] = $form_state['values'][$element['#name']]['all_day_max_time'];
  }
  return $element;
}

function _mm_schedule_rrule_after_build($element, &$form_state) {
  if (isset($element['FREQ'])) {
    // Change "Days" to "Day(s)" (etc.) in the frequency list
    $element['FREQ']['#options'] = preg_replace('{s$}', '(s)', $element['FREQ']['#options']);
  }

  if (isset($element['advanced'])) {
    // Wordsmithing
    $element['advanced']['#title'] = t('More options for recurring events');
    $element['advanced']['#description'] = t('If your recurring event will not occur on regularly repeating days, select the specific months and days that your event will recur. Use the “Except” box for days that the event will not take place (such as a holiday).');
  }

  return $element;
}

function _mm_schedule_date_timestamp_get($date) {
  return isset($date->timestamp) ? $date->timestamp : $date->format('U');
}

function _mm_schedule_can_add_event($calendar_mmtid) {
  return $calendar_mmtid && mm_content_user_can($calendar_mmtid, 'u') && user_access('create mm_event content') && (user_access('administer all menus') || array_search('mm_event', mm_content_resolve_cascaded_setting('allowed_node_types', $calendar_mmtid, $types_at, $types_parent)) !== FALSE);
}

function _mm_schedule_date_combo_js($id, $name, $delta = '') {
  if (!empty($delta)) $delta = "-$delta";
  return <<<EOJ
Drupal.behaviors.MMDateCombo = function(context) {
  \$('#{$id}-value{$delta}-wrapper:not(.mm-date-combo-processed)', context)
    .addClass('mm-date-combo-processed')
    .parents('fieldset')
      .each(function() {
        var check = \$('#{$id}-is-all-day{$delta}');
        var outerDivs = \$('#{$id}-value{$delta}-timeEntry-popup-1-wrapper,#{$id}-value2{$delta}-timeEntry-popup-1-wrapper', this);
        if (check.attr('checked'))
          outerDivs.hide();
        check.click(function() {
          this.checked ? outerDivs.hide('fast') : outerDivs.show('fast');
        });
      });
};
EOJ;
}

function _mm_schedule_subrequest_js($id, $url, $del_selector = '') {
  $del_js = $del_selector ? '$(\'' . $del_selector . '\').fadeOut(5000);' : '';
  return <<<EOJ
  \$('#$id:not(.$id-processed)')
    .addClass('$id-processed')
    .click(function() {
      this.blur();
      if (\$(this).attr('disabled')) return false;
      var body = \$('#calpopup-body');
      var div = \$('<div id="calpopup-body-result"><img src="' + var_path + '/images/throbber.gif" id="popthrobber-result" /></div>')
        .css('top', body[0].offsetTop)
        .insertAfter(body);
      \$.ajax({
        type:  "GET",
        url:   Drupal.settings.basePath + "$url",
        error: function(req, status) {
          div
            .html(status)
            .fadeOut(5000);
        },
        success: function(msg) {
          div
            .html(msg)
            .fadeOut(5000);
          \$('#$id')
            .attr('disabled', true)
            .fadeOut(5000);$del_js
        }
      });
      return false;
    });
EOJ;
}

function _mm_schedule_view_course($section_id, $instr_method) {
  $week_day = academics_day_list();
  $instr_method_parts = explode('?', $instr_method);
  $instr_method = str_replace(MM_SCHEDULE_INSTRUCTION_SLASH, '/', $instr_method_parts[0]);
  $courses = db_query(
    'SELECT d.sectionid, d.instr_method, s.title, start_time, end_time, weekday, bldg, room FROM {univ_section} s '.
      'INNER JOIN {univ_section_detail} d ON s.sectionid = d.sectionid '.
    "WHERE s.sectionid = '%s' AND d.instr_method = '%s'",
    $section_id, $instr_method);

  $title = $preferredname = $start_time = $end_time = $bldg = $room = '';
  $weekday = array();
  while ($course = db_fetch_object($courses)) {
    $instructors = db_query(
      'SELECT preferredname FROM {eduprofile} e '.
        'INNER JOIN {univ_section_faculty} f ON f.idnumber = e.idnumber '.
      "WHERE sectionid = '%s' AND instr_method = '%s'",
      $course->sectionid, $course->instr_method);
    $instruct_list = array();
    while ($instructor = db_fetch_object($instructors)) {
      $instruct_list[] = $instructor->preferredname;
    }

    if (empty($title))         $title         = $course->title;
    if (empty($preferredname)) $preferredname = implode(', ', $instruct_list);
    if (empty($start_time))    $start_time    = $course->start_time;
    if (empty($end_time))      $end_time      = $course->end_time;
    if (empty($bldg))          $bldg          = $course->bldg;
    if (empty($room))          $room          = $course->room;
    $weekday[$course->weekday] = TRUE;
  }

  $output = '<h3>' . $title . '</h3>';
  $output .= 'Instructor(s): ' . $preferredname . '<br />';
  $output .= 'Time: ';
  $temp_weekdays = array();
  foreach ($week_day as $key => $value) {
    if ($weekday[$key]) $temp_weekdays[] = $value;
  }
  $output .= implode(', ', $temp_weekdays) . ' from ';
  $output .= trim($start_time, 0) . ' - ' . trim($end_time, 0) . '<br />';
  if (!empty($bldg) || !empty($room)) {
    $output .= 'Location: ' . $bldg . ' ' . $room . '<br />';
  }
  print $output;
  $GLOBALS['devel_shutdown'] = FALSE;
  exit();
}
